version: '3.8'

services:
  paper:
    image: "itzg/minecraft-server:java${JAVA_VERSION}"
    stdin_open: true
    container_name: paper-dev-server-${PAPER_VERSION}
    ports:
      - "25565:25565"
      - "5005:5005"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "${PAPER_VERSION}"
      JVM_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=0.0.0.0:5005"
      JAVA_VERSION: "${JAVA_VERSION}"
      PLUGINS: "${SKRIPT_URL}"
    volumes:
      - "${PROJECT_ROOT}/docker/plugins:/plugins"
      - "${PROJECT_ROOT}/test/scripts:/data/plugins/Skript/scripts"
      - "${PROJECT_ROOT}/docker/server-data/${PAPER_VERSION}:/data"