class FunctionDefinitionClass:
    function nonParameterFunction():
        send "nonParameterFunction" to console

    function hasParameterFunction(param1: long, param2: long):
        send "parameterFunction param1=%[param1]%, param2=%[param2]%" to console

    function nonParameterAndReturnFunction() :: long:
        return 10

    function hasParameterAndReturnFunction(param1: long, param2: long) :: long:
        return [param1] + [param2]

load:
    val functionDefinitionClass := new FunctionDefinitionClass

    [functionDefinitionClass] -> nonParameterFunction()
    [functionDefinitionClass] -> hasParameterFunction(5, 10)

    val result1 := [functionDefinitionClass] -> nonParameterAndReturnFunction()
    send "result1=%[result1]%" to console

    val result2 := [functionDefinitionClass] -> hasParameterAndReturnFunction(5, 10)
    send "result2=%[result2]%" to console