name: Test ReactiveSk

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/*.jar
  test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        include:
          - skript-version: '2.6.3'
            module: 'ReactiveSk-skript-v2_6_3'
          - skript-version: '2.6.4'
            module: 'ReactiveSk-skript-v2_6_3'
          - skript-version: '2.7.0'
            module: 'ReactiveSk-skript-v2_7_0'
          - skript-version: '2.8.0'
            module: 'ReactiveSk-skript-v2_7_0'
          - skript-version: '2.9.0'
            module: 'ReactiveSk-skript-v2_7_0'
          - skript-version: '2.9.5'
            module: 'ReactiveSk-skript-v2_7_0'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: extra-plugins/
          merge-multiple: true
      - name: Run tests
        uses: SkriptLang/skript-test-action@v1.2
        with:
          test_script_directory: test/scripts
          skript_repo_ref: ${{ matrix.skript-version }}
          extra_plugins_directory: extra-plugins
